### ISSUE TITLE
Lambda functions are failing on AWS

### ISSUE THREAD

**Issue by arun-gupta** [aws-samples/aws-microservices-deploy-options#146]
Invoking the Lambda function on AWS is giving the following error:

```
lambda $ curl `aws cloudformation \
>   describe-stacks \
>   --stack-name aws-microservices-deploy-options-lambda \
>   --query "Stacks[].Outputs[?OutputKey=='GreetingApiEndpoint'].[OutputValue]" \
>   --output text`
{"message": "Internal server error"}lambda $ curl `aws cloudformation \
>   describe-stacks \
>   --stack-name aws-microservices-deploy-options-lambda \
>   --query "Stacks[].Outputs[?OutputKey=='NamesApiEndpoint'].[OutputValue]" \
>   --output text`
{"message": "Internal server error"}
```

**Comment by arun-gupta** [comment]
Testing locally shows the following error:

```
START RequestId: fc33406d-f6f3-4be9-8868-fcb41d2b8cca Version: $LATEST
java.lang.ClassNotFoundException: org.aws.samples.compute.greeting.GreetingHandler
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
```
